apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp2-encrypted
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  # this is using the private key's of the region in AWS.
  # In practice we'd encrypt this with a key we own and is managed in something like Vault or KMS
  encrypted: "true"
reclaimPolicy: Retain
#mountOptions:
# - debug
