apiVersion: apps/v1
kind: Deployment
metadata:
  name: docustore-frontend
  labels:
    app: docustore-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docustore-frontend
  template:
    metadata:
      labels:
        app: docustore-frontend
    spec:
      containers:
      - name: nginx
        image: pathogen/docustore-frontend:v0.0.1
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: backend-url
        - name: APP_NAME
          value: "Super Duper Document App"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: docustore-frontend-config