apiVersion: v1
kind: Namespace
metadata:
  name: affinity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-deployment
  namespace: affinity
spec:
  replicas: 4
  selector:
    matchLabels:
      app: affinity-app
  template:
    metadata:
      labels:
        app: affinity-app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: sleeper
        image: ubuntu
        command: ["sleep", "infinity"]
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - affinity-app
              topologyKey: kubernetes.io/hostname

