apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "* * * * *" # every minute. doesn't get smaller than that
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-container
            image: busybox
            command: ["sh", "-c", "echo 'Hello from the Kubernetes CronJob!'"]
          restartPolicy: OnFailure