apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-namespaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-reader
subjects:
- kind: ServiceAccount
  name: kubectl-sa
---
apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
spec:
  containers:
  - name: kubectl-container
    image: bitnami/kubectl:latest
    command:
    - /bin/sh
    - -c
    - sleep infinity
  serviceAccountName: kubectl-sa