apiVersion: v1
kind: Namespace
metadata:
  name: sidecar
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-sidecar
  namespace: sidecar
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx
  - name: log-tailer
    image: busybox
    args:
    - /bin/sh
    - -c
    - "tail -f /var/log/nginx/access.log"
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx
  volumes:
  - name: nginx-logs
    emptyDir: {}

